#line 2 "tokens.c"

#line 4 "tokens.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yyget_lval
#define yyget_lval_ALREADY_DEFINED
#else
#define yyget_lval yyget_lval
#endif

#ifdef yyset_lval
#define yyset_lval_ALREADY_DEFINED
#else
#define yyset_lval yyset_lval
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 127
#define YY_END_OF_BUFFER 128
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[521] =
    {   0,
        0,    0,  128,  126,  125,  125,  113,  126,  119,  112,
      126,  107,  108,  117,  116,  104,  115,  111,  118,   70,
       69,  105,  101,  120,  106,  121,  124,   67,   67,  109,
      110,  122,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,  102,
      123,  103,  114,  125,    4,    6,   67,  100,    0,   78,
        0,   86,  103,   95,   87,    0,    0,    0,   84,   92,
       82,   93,   83,   94,    0,   73,    1,    2,   85,   74,
       70,    0,    0,   70,   70,    0,   70,   69,   69,   69,
       69,  110,  102,  109,   91,   97,   99,   98,   90,   67,

        0,    0,   88,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   15,   67,
       67,   67,   67,   67,   67,   67,   23,   59,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   89,   96,    0,    4,    6,    0,    0,    6,
        6,    6,   67,   78,    0,    0,    0,    0,   71,    0,
        0,    0,   79,    0,   73,    2,    0,   74,    0,   72,
       70,   70,   70,   70,    0,   68,   69,   69,   69,   69,
       81,   80,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,

       67,   67,   67,   67,   21,   67,   67,   25,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,    0,    0,
        6,   67,    0,    0,    0,    0,    0,    0,   73,    0,
       74,   72,   70,    0,    0,   68,    0,   68,   68,   69,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
        8,   67,   10,   11,   67,   67,   67,   67,   17,   18,
       67,   67,   67,   67,   22,   67,   26,    0,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   39,   67,   67,    0,    0,    6,    0,

        7,    0,    0,    0,    0,    0,    0,    0,   68,   68,
        0,   75,   68,   68,   67,   67,   45,   67,   67,   67,
       67,   67,   67,   67,    9,   12,   67,   67,   67,   67,
        0,   20,   67,   67,    0,    0,    0,    0,   67,   67,
       67,   67,   30,   67,   67,   67,   67,   67,   60,   67,
       37,   67,   67,   67,   41,    0,    5,    0,    0,   76,
        0,   77,   75,   68,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   16,   19,    0,   67,   24,
        0,    0,    0,    0,   67,   67,   67,   29,   31,   32,
       33,   34,   35,   67,   67,   67,   67,    0,    3,    0,

        5,   58,   76,   77,   67,   67,   44,   67,   67,   67,
       67,   67,   67,   67,   67,   14,    0,   65,    0,    0,
        0,    0,    0,   67,   67,   67,   36,   67,    0,   67,
        3,    0,    0,   42,   43,   46,   47,   67,   67,   67,
       67,   52,   13,    0,   67,    0,    0,    0,    0,    0,
       67,   27,   28,   38,    0,   40,    0,    0,   67,   49,
       67,   67,    0,   66,   66,   66,   66,    0,    0,    0,
        0,    0,   61,    0,    0,    0,   48,   67,   67,    0,
       66,   66,   66,   66,    0,   53,   55,   54,    0,    0,
       67,   67,   56,   66,   66,   66,    0,    0,    0,   67,

       67,   66,   66,   66,    0,   67,   51,   62,   66,   66,
       57,   50,   66,   66,   66,   66,   66,   63,   64,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    4,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
       36,   37,   38,   37,   37,   39,   40,   41,   42,   43,
       37,   37,   44,   45,   46,   37,   37,   47,   37,   37,
       48,   49,   50,   51,   52,    1,   53,   54,   55,   56,

       57,   58,   59,   60,   61,   37,   62,   63,   64,   65,
       66,   67,   37,   68,   69,   70,   71,   72,   73,   74,
       75,   76,   77,   78,   79,   80,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[81] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    1,    4,
        1,    1,    1,    1,    1,    1,    5,    1,    6,    6,
        7,    7,    1,    1,    1,    1,    1,    3,    1,    7,
        7,    7,    7,    7,    7,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    1,    3,    1,
        1,    8,    6,    6,    7,    7,    7,    6,    8,    8,
        8,    8,    8,    8,    9,    8,    8,    9,    8,    9,
        8,    9,    8,    9,    8,    8,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[539] =
    {   0,
        0,   79,  955,  956,  956,  956,  928,   76,   57,   76,
      904,  897,  956,  925,   73,  956,   74,   72,   85,  109,
      118,  923,  956,   87,  923,   70,  956,    0,   99,  956,
      956,  922,  146,  876,  878,   54,   49,   53,   70,  879,
       59,  878,  886,  885,   81,   78,  139,   93,  881,  956,
       93,  956,  956,  163,  938,  102,  899,  956,  157,  191,
      142,  956,  956,  956,  956,  124,  148,  872,  956,  956,
      956,  956,  956,  956,  920,  189,  956,    0,  956,  214,
      221,  266,  198,  161,  140,  919,  150,  274,  205,  162,
      193,  956,  956,  956,  909,  956,  956,  956,  908,    0,

      180,  884,  956,  187,  866,  865,  873,  865,  862,  857,
      866,  867,  854,  866,  853,  868,  855,  861,  847,  848,
      845,  845,  859,  847,  844,  841,    0,  191,  845,  836,
      210,  842,  126,   79,  846,  853,  838,  898,  204,  835,
      207,  841,  956,  956,  296,  899,  225,  860,  295,    0,
      243,  842,  855,  303,  891,  253,  313,    0,  956,  291,
        0,  831,  956,  308,  956,    0,  332,  956,  336,  344,
       98,  956,  856,  831,    0,  304,  128,  956,  854,  829,
      956,  956,  830,  824,  823,  824,  822,  833,  817,  831,
      815,  811,  815,  827,  822,  810,  220,  824,  822,  818,

      810,  816,  815,  818,  813,  803,  807,    0,  808,  332,
      795,  804,  794,  792,  794,  796,  803,  789,  787,  787,
      801,  798,  788,  792,  782,  795,  797,  786,  805,  366,
      789,  358,  370,  414,  362,  463,  777,  372,  379,  384,
      467,  956,  956,  215,  259,  338,  407,  334,  367,  956,
      786,  780,  780,  775,  784,  781,  782,  768,  780,  771,
        0,  773,    0,    0,  764,  772,  761,  768,    0,    0,
      762,  413,  759,  775,    0,  762,    0,  457,  771,  756,
      756,  755,  752,  764,  754,  758,  763,  762,  759,  759,
      749,  754,  755,    0,  741,  753,  359,  406,  807,  420,

      956,  182,    0,  329,    0,  738,  436,  489,  393,  956,
      455,  512,  768,  743,  740,  743,    0,  740,  734,  740,
      730,  738,  745,  742,    0,    0,  731,  732,  737,  728,
      476,    0,  737,  734,  737,  734,  731,  730,  716,  715,
      723,  707,    0,  715,  711,  704,  680,  681,    0,  666,
        0,  655,  645,  656,    0,  269,    0,  701,  516,  520,
      524,  541,  956,  956,  387,  657,  653,  639,  624,  616,
      623,  614,  617,  597,  596,    0,    0,  608,  604,    0,
      608,  609,  596,  386,  599,  601,  602,    0,    0,    0,
        0,    0,    0,  598,  598,  488,  584,  475,    0,  480,

        0,  956,  956,  956,  577,  587,    0,  570,  588,  589,
      573,  584,  583,  582,  576,    0,  577,  579,  573,  566,
      559,  557,  556,  559,  554,  551,    0,  563,  554,  561,
        0,  546,    0,    0,    0,    0,    0,  548,  550,  561,
      550,    0,    0,  542,  552,  565,  558,  544,  543,  549,
      540,    0,    0,    0,  548,    0,  571,  618,  527,    0,
      532,  534,  532,    0,  537,  535,  525,  582,  513,  511,
      496,  479,    0,  496,  501,    0,    0,  459,  468,  454,
        0,  453,  449,  443,  444,  956,  956,  956,  585,  403,
      408,  409,  956,  388,  386,  373,  370,  590,  371,  342,

      333,  339,  315,  299,  276,  271,    0,    0,  243,  250,
      956,    0,  202,  160,  149,   54,   23,    0,    0,  956,
      676,  685,  689,  698,  705,  712,  721,  726,  728,  730,
      732,  739,  748,  757,  764,  768,  770,  774
    } ;

static const flex_int16_t yy_def[539] =
    {   0,
      520,    1,  520,  520,  520,  520,  520,  521,  520,  520,
      522,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  523,  523,  520,
      520,  520,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  520,
      520,  520,  520,  520,  520,  524,  523,  520,  521,  520,
      525,  520,  520,  520,  520,  522,  526,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  527,  520,  520,
      520,  520,  520,  520,  520,  528,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  523,

      521,  522,  520,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  520,  520,  520,  520,  524,  520,  520,  524,
      524,  524,  523,  520,  520,  520,  521,  529,  520,  522,
      530,  520,  520,  520,  520,  527,  520,  520,  520,  520,
      520,  520,  520,  520,  531,  528,  520,  520,  520,  520,
      520,  520,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,

      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  520,  520,
      524,  523,  521,  521,  522,  522,  520,  520,  520,  520,
      520,  520,  520,  531,  531,  520,  520,  520,  520,  520,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  520,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  520,  520,  524,  520,

      520,  521,  234,  522,  236,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      520,  523,  523,  523,  520,  520,  520,  520,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  532,  533,  520,  520,  520,
      520,  520,  520,  520,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  520,  523,  523,
      520,  520,  520,  520,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  523,  532,  534,  535,

      533,  520,  520,  520,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  520,  523,  520,  520,
      520,  520,  520,  523,  523,  523,  523,  523,  520,  523,
      534,  532,  536,  523,  523,  523,  523,  523,  523,  523,
      523,  523,  523,  520,  537,  520,  520,  520,  520,  520,
      523,  523,  523,  523,  520,  523,  532,  532,  523,  523,
      523,  523,  520,  538,  538,  538,  538,  520,  520,  520,
      520,  520,  523,  520,  532,  458,  523,  523,  523,  520,
      538,  538,  538,  538,  520,  520,  520,  520,  520,  520,
      523,  523,  520,  538,  538,  538,  520,  520,  520,  523,

      523,  538,  538,  538,  520,  523,  523,  538,  538,  538,
      520,  523,  538,  538,  538,  538,  538,  538,  538,    0,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520
    } ;

static const flex_int16_t yy_nxt[1037] =
    {   0,
        4,    5,    6,    5,    7,    8,    4,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       21,   21,   22,   23,   24,   25,   26,   27,    4,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   29,   28,
       28,   28,   28,   28,   28,   29,   28,   30,    4,   31,
       32,   33,   34,   35,   36,   37,   38,   39,   40,   28,
       41,   28,   42,   28,   43,   28,   28,   44,   45,   46,
       47,   48,   49,   28,   28,   28,   50,   51,   52,   53,
       54,   60,   62,   63,   64,   55,   70,  519,   75,   72,
       76,   76,   76,   76,   93,   98,   99,   77,   71,   73,

       74,   65,   78,  151,  101,  118,  115,   56,  102,   94,
       79,   95,   96,  116,  119,  120,  127,  121,  143,  117,
       57,  518,  123,  128,   61,   80,  122,   81,   81,   82,
       82,  218,  124,  159,   80,  125,   88,   88,   88,   88,
      132,  133,   83,  172,  101,  136,  219,   84,  102,  140,
      134,   83,  137,  135,   85,   86,   89,  152,  141,  138,
      157,  157,   60,   90,  145,   83,  160,  160,  172,  146,
      144,   87,   67,  178,   83,  104,  105,  106,  173,   85,
       91,  107,   86,  108,  216,   60,  109,   60,   90,  110,
      111,  147,  154,  154,  154,  172,  101,  112,  178,  171,

      179,  217,  174,  139,  148,   61,  172,   76,   76,   76,
       76,  169,  171,  169,  517,  158,  170,  170,  170,  170,
      172,  161,  164,  165,  180,  516,  151,  165,   61,  155,
       61,  172,   76,   76,   76,   76,  155,   80,  178,   81,
       81,   82,   82,  177,  151,  164,  165,  167,  168,  183,
      178,  165,  168,  207,   83,  177,  184,  307,  101,   84,
      208,  156,  515,  178,  223,  211,   85,  226,  212,  227,
      167,  168,  224,  155,  399,  178,  168,   83,  213,  214,
      152,  307,   80,   87,   82,   82,   82,   82,  265,  266,
       80,   85,   88,   88,   88,   88,  149,  145,  152,   83,

      159,  308,  146,  514,  154,  154,  154,   83,  101,  235,
      235,  513,   89,  230,  230,  230,  230,  400,   60,   90,
      245,  238,   83,  238,  147,  308,  239,  239,  239,  239,
       83,  233,  233,  278,  278,  278,   91,  148,  159,   67,
      512,  155,  246,  511,   90,  240,  247,  240,  155,  248,
      241,  241,  241,  241,  170,  170,  170,  170,  510,  300,
      300,   61,  170,  170,  170,  170,  249,  298,  301,  301,
      247,  159,  313,  156,  248,   60,  309,   67,  242,  509,
      304,  304,  242,  310,  230,  230,  230,  230,  302,  302,
      239,  239,  239,  239,  508,  507,  314,  239,  239,  239,

      239,  242,  241,  241,  241,  241,  242,  298,  310,  506,
       67,  356,  310,  165,  331,  331,  331,  165,   61,   60,
      311,  300,  311,  505,  422,  312,  312,  312,  312,  309,
      301,  504,  303,  303,  303,  303,  165,  310,  310,  405,
      422,  165,  503,  303,  303,  303,  303,  303,  303,  359,
      502,  359,  406,  423,  360,  360,  360,  360,  278,  278,
      278,  501,   61,  310,  500,  499,  303,  303,  303,  303,
      303,  303,  159,  312,  312,  312,  312,  331,  331,  331,
      399,  305,  305,  305,  305,  241,  241,  241,  241,  429,
      429,  429,  305,  305,  305,  305,  305,  305,  432,  432,

      497,  168,  361,  496,  361,  168,  399,  362,  362,  362,
      362,   67,  495,  494,  335,  305,  305,  305,  305,  305,
      305,  493,  492,  400,  168,  336,  337,  491,  338,  168,
      312,  312,  312,  312,  360,  360,  360,  360,  360,  360,
      360,  360,  362,  362,  362,  362,  363,  378,  490,  400,
      363,  399,  489,  433,  403,  429,  429,  429,  403,  362,
      362,  362,  362,  488,  457,  457,  468,  468,  468,  363,
      100,  100,  100,  100,  363,  404,  399,  403,  487,  404,
      486,  484,  403,  468,  468,  468,  498,  498,  498,  475,
      475,  498,  498,  498,  400,  483,  482,  480,  404,  479,

      478,  477,  474,  404,  473,  472,  465,  466,  471,  470,
      469,  463,  462,  461,  460,  459,  467,  456,  454,  400,
      453,  452,  455,  399,  451,  450,  449,  448,  447,  446,
      445,  444,  443,  442,  441,  440,  476,  476,  476,  476,
      439,  438,  437,  436,  435,  434,  430,  476,  476,  476,
      476,  476,  476,  485,  428,  427,  426,  425,  336,  424,
      421,  420,  419,  418,  417,  416,  400,  415,  414,  413,
      476,  476,  476,  476,  476,  476,   59,  412,   59,   59,
       59,   59,   59,   59,   59,   66,  411,   66,  410,   66,
       66,   66,   66,   66,  100,  100,  100,  100,  150,  409,

      150,  150,  150,  150,  150,  150,  150,   59,   59,  408,
       59,  407,  402,   59,   66,   66,  397,   66,  396,  395,
       66,  166,  394,  166,  166,  166,  166,  166,  166,  166,
      176,  176,  176,  234,  234,  236,  236,  244,  244,  398,
      393,  398,  398,  398,  398,  398,  398,  398,  401,  392,
      401,  401,  401,  401,  401,  401,  401,  431,  391,  431,
      431,  431,  431,  431,  431,  431,  398,  398,  390,  398,
      389,  388,  398,  458,  458,  464,  464,  464,  464,  481,
      481,  481,  481,  387,  386,  385,  384,  383,  382,  381,
      380,  379,  377,  376,  375,  374,  373,  372,  371,  370,

      369,  368,  367,  366,  365,  364,  364,  358,  357,  355,
      354,  353,  352,  351,  350,  349,  348,  347,  346,  345,
      344,  343,  342,  341,  340,  339,  334,  333,  332,  330,
      329,  328,  327,  326,  325,  324,  323,  322,  321,  320,
      319,  318,  317,  316,  315,  306,  299,  297,  296,  295,
      294,  293,  292,  291,  290,  289,  288,  287,  286,  285,
      284,  283,  282,  281,  280,  279,  277,  276,  275,  274,
      273,  272,  271,  270,  269,  268,  267,  264,  263,  262,
      261,  260,  259,  258,  257,  256,  255,  254,  253,  252,
      251,  250,  250,  243,  243,  237,  101,  232,  231,  229,

      149,  228,  225,  101,  222,  221,  220,  215,  210,  209,
      206,  205,  204,  203,  202,  201,  200,  199,  198,  197,
      196,  195,  194,  193,  192,  191,  190,  189,  188,  187,
      186,  185,   67,  182,  181,  175,  163,  162,  153,  149,
      142,  131,  130,  129,  126,  114,  113,  103,   97,   92,
       69,   68,   67,   58,  520,    3,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,

      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520
    } ;

static const flex_int16_t yy_chk[1037] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        2,    8,    9,    9,   10,    2,   15,  517,   18,   17,
       18,   18,   18,   18,   24,   26,   26,   19,   15,   17,

       17,   10,   19,   56,   29,   37,   36,    2,   29,   24,
       19,   24,   24,   36,   37,   38,   41,   38,   51,   36,
        2,  516,   39,   41,    8,   20,   38,   20,   20,   20,
       20,  134,   39,   66,   21,   39,   21,   21,   21,   21,
       45,   45,   20,  171,   47,   46,  134,   20,   47,   48,
       45,   21,   46,   45,   20,   20,   21,   56,   48,   47,
       61,   61,   59,   21,   54,   20,   67,   67,  171,   54,
       51,   20,   66,  177,   21,   33,   33,   33,   85,   20,
       21,   33,   20,   33,  133,  101,   33,  302,   21,   33,
       33,   54,   60,   60,   60,   87,   60,   33,  177,   84,

       90,  133,   85,   47,   54,   59,   84,   76,   76,   76,
       76,   83,   87,   83,  515,   61,   83,   83,   83,   83,
       87,   67,   76,   76,   90,  514,  147,   76,  101,   60,
      302,   84,   80,   80,   80,   80,   60,   81,   91,   81,
       81,   81,   81,   89,  151,   76,   76,   80,   80,  104,
       89,   76,   80,  128,   81,   91,  104,  244,  156,   81,
      128,   60,  513,   91,  139,  131,   81,  141,  131,  141,
       80,   80,  139,  156,  356,   89,   80,   81,  131,  131,
      147,  244,   82,   81,   82,   82,   82,   82,  197,  197,
       88,   81,   88,   88,   88,   88,  149,  145,  151,   82,

      160,  245,  145,  510,  154,  154,  154,   88,  154,  160,
      160,  509,   88,  149,  149,  149,  149,  356,  157,   88,
      176,  164,   82,  164,  145,  245,  164,  164,  164,  164,
       88,  157,  157,  210,  210,  210,   88,  145,  304,  160,
      506,  154,  176,  505,   88,  167,  176,  167,  154,  176,
      167,  167,  167,  167,  169,  169,  169,  169,  504,  232,
      297,  157,  170,  170,  170,  170,  176,  230,  232,  297,
      176,  235,  248,  154,  176,  233,  246,  304,  170,  503,
      235,  235,  170,  246,  230,  230,  230,  230,  233,  233,
      238,  238,  238,  238,  502,  501,  248,  239,  239,  239,

      239,  170,  240,  240,  240,  240,  170,  298,  246,  500,
      235,  298,  249,  239,  272,  272,  272,  239,  233,  234,
      247,  300,  247,  499,  497,  247,  247,  247,  247,  249,
      300,  496,  234,  234,  234,  234,  239,  249,  309,  365,
      384,  239,  495,  234,  234,  234,  234,  234,  234,  307,
      494,  307,  365,  384,  307,  307,  307,  307,  278,  278,
      278,  492,  234,  309,  491,  490,  234,  234,  234,  234,
      234,  234,  236,  311,  311,  311,  311,  331,  331,  331,
      398,  236,  236,  236,  236,  241,  241,  241,  241,  396,
      396,  396,  236,  236,  236,  236,  236,  236,  400,  400,

      485,  241,  308,  484,  308,  241,  475,  308,  308,  308,
      308,  236,  483,  482,  278,  236,  236,  236,  236,  236,
      236,  480,  479,  398,  241,  278,  278,  478,  278,  241,
      312,  312,  312,  312,  359,  359,  359,  359,  360,  360,
      360,  360,  361,  361,  361,  361,  312,  331,  474,  475,
      312,  432,  472,  400,  360,  429,  429,  429,  360,  362,
      362,  362,  362,  471,  432,  432,  446,  446,  446,  312,
      445,  445,  445,  445,  312,  362,  457,  360,  470,  362,
      469,  467,  360,  468,  468,  468,  489,  489,  489,  457,
      457,  498,  498,  498,  432,  466,  465,  463,  362,  462,

      461,  459,  455,  362,  451,  450,  445,  445,  449,  448,
      447,  444,  441,  440,  439,  438,  445,  430,  428,  457,
      426,  425,  429,  458,  424,  423,  422,  421,  420,  419,
      418,  417,  415,  414,  413,  412,  458,  458,  458,  458,
      411,  410,  409,  408,  406,  405,  397,  458,  458,  458,
      458,  458,  458,  468,  395,  394,  387,  386,  498,  385,
      383,  382,  381,  379,  378,  375,  458,  374,  373,  372,
      458,  458,  458,  458,  458,  458,  521,  371,  521,  521,
      521,  521,  521,  521,  521,  522,  370,  522,  369,  522,
      522,  522,  522,  522,  523,  523,  523,  523,  524,  368,

      524,  524,  524,  524,  524,  524,  524,  525,  525,  367,
      525,  366,  358,  525,  526,  526,  354,  526,  353,  352,
      526,  527,  350,  527,  527,  527,  527,  527,  527,  527,
      528,  528,  528,  529,  529,  530,  530,  531,  531,  532,
      348,  532,  532,  532,  532,  532,  532,  532,  533,  347,
      533,  533,  533,  533,  533,  533,  533,  534,  346,  534,
      534,  534,  534,  534,  534,  534,  535,  535,  345,  535,
      344,  342,  535,  536,  536,  537,  537,  537,  537,  538,
      538,  538,  538,  341,  340,  339,  338,  337,  336,  335,
      334,  333,  330,  329,  328,  327,  324,  323,  322,  321,

      320,  319,  318,  316,  315,  314,  313,  306,  299,  296,
      295,  293,  292,  291,  290,  289,  288,  287,  286,  285,
      284,  283,  282,  281,  280,  279,  276,  274,  273,  271,
      268,  267,  266,  265,  262,  260,  259,  258,  257,  256,
      255,  254,  253,  252,  251,  237,  231,  229,  228,  227,
      226,  225,  224,  223,  222,  221,  220,  219,  218,  217,
      216,  215,  214,  213,  212,  211,  209,  207,  206,  205,
      204,  203,  202,  201,  200,  199,  198,  196,  195,  194,
      193,  192,  191,  190,  189,  188,  187,  186,  185,  184,
      183,  180,  179,  174,  173,  162,  155,  153,  152,  148,

      146,  142,  140,  138,  137,  136,  135,  132,  130,  129,
      126,  125,  124,  123,  122,  121,  120,  119,  118,  117,
      116,  115,  114,  113,  112,  111,  110,  109,  108,  107,
      106,  105,  102,   99,   95,   86,   75,   68,   57,   55,
       49,   44,   43,   42,   40,   35,   34,   32,   25,   22,
       14,   12,   11,    7,    3,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,

      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[128] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "tokens.lex"
/**
# Lexer for Basilisk C

Closely based on the [C99 lexer](c.lex). */
#line 33 "tokens.lex"
#include <stdio.h>
#include <assert.h>
#include "parser.h"
#include "basilisk.h"

#define YYSTYPE Ast *
#define YY_DECL int yylex (YYSTYPE * yylval_param, AstRoot * parse)
 
static void comment (void);
static void preproc (void);
static void bpreproc (void);
static void ompreproc (void);
static void file_line (AstRoot * parse, const char * text);
static int  check_type (AstRoot * parse);

static Ast * new_ast (AstRoot * parse,
		      int token, int line, char * start, char * end)
{
  Allocator * alloc = parse->alloc;
  Ast * n = allocate (alloc, sizeof(AstTerminal));
  memset (n, 0, sizeof(AstTerminal));
  n->sym = token_symbol (token);
  AstTerminal * t = ast_terminal (n);
  t->start = start;
  t->after = end;
  t->file = parse->file[parse->nf - 1];
  while (start != end) {
    if (*start == '\n')
      line--;
    start++;
  }
  t->line = line;
  return n;
}

#define CAST()								\
  *yylval = new_ast (parse, yytext[0], yylineno, yytext, yytext);	\
  return yytext[0];
  
#define SAST(t) 							\
  *yylval = new_ast (parse, t, yylineno, yytext, yytext + strlen(yytext) - 1); \
  return t;
  
#line 940 "tokens.c"
#line 941 "tokens.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

YYSTYPE * yyget_lval ( void );

void yyset_lval ( YYSTYPE * yylval_param  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex \
               (YYSTYPE * yylval_param );

#define YY_DECL int yylex \
               (YYSTYPE * yylval_param )
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
        YYSTYPE * yylval;
    
    yylval = yylval_param;

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 78 "tokens.lex"


#line 1172 "tokens.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 521 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 956 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 80 "tokens.lex"
{ comment(); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 81 "tokens.lex"
{ /* consume //-comment */ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 82 "tokens.lex"
{ file_line (parse, yytext); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 83 "tokens.lex"
{ preproc(); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 84 "tokens.lex"
{ bpreproc(); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 85 "tokens.lex"

	YY_BREAK
case 7:
YY_RULE_SETUP
#line 86 "tokens.lex"
{ ompreproc(); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 88 "tokens.lex"
{ SAST(AUTO); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 89 "tokens.lex"
{ SAST(BREAK); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 90 "tokens.lex"
{ SAST(CASE); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 91 "tokens.lex"
{ SAST(CHAR); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 92 "tokens.lex"
{ SAST(CONST); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 93 "tokens.lex"
{ SAST(CONTINUE); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 94 "tokens.lex"
{ SAST(DEFAULT); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 95 "tokens.lex"
{ SAST(DO); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 96 "tokens.lex"
{ SAST(DOUBLE); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 97 "tokens.lex"
{ SAST(ELSE); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 98 "tokens.lex"
{ SAST(ENUM); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 99 "tokens.lex"
{ SAST(EXTERN); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 100 "tokens.lex"
{ SAST(FLOAT); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 101 "tokens.lex"
{ SAST(FOR); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 102 "tokens.lex"
{ SAST(GOTO); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 103 "tokens.lex"
{ SAST(IF); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 104 "tokens.lex"
{ SAST(INLINE); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 105 "tokens.lex"
{ SAST(INT); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 106 "tokens.lex"
{ SAST(LONG); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 107 "tokens.lex"
{ SAST(REGISTER); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 108 "tokens.lex"
{ SAST(RESTRICT); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 109 "tokens.lex"
{ SAST(RETURN); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 110 "tokens.lex"
{ SAST(SHORT); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 111 "tokens.lex"
{ SAST(SIGNED); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 112 "tokens.lex"
{ SAST(SIZEOF); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 113 "tokens.lex"
{ SAST(STATIC); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 114 "tokens.lex"
{ SAST(STRUCT); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 115 "tokens.lex"
{ SAST(SWITCH); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 116 "tokens.lex"
{ SAST(TYPEDEF); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 117 "tokens.lex"
{ SAST(UNION); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 118 "tokens.lex"
{ SAST(UNSIGNED); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 119 "tokens.lex"
{ SAST(VOID); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 120 "tokens.lex"
{ SAST(VOLATILE); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 121 "tokens.lex"
{ SAST(WHILE); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 122 "tokens.lex"
{ SAST(ALIGNAS); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 123 "tokens.lex"
{ SAST(ALIGNOF); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 124 "tokens.lex"
{ SAST(ATOMIC); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 125 "tokens.lex"
{ SAST(BOOL); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 126 "tokens.lex"
{ SAST(COMPLEX); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 127 "tokens.lex"
{ SAST(GENERIC); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 128 "tokens.lex"
{ SAST(IMAGINARY); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 129 "tokens.lex"
{ SAST(NORETURN); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 130 "tokens.lex"
{ SAST(STATIC_ASSERT); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 131 "tokens.lex"
{ SAST(THREAD_LOCAL); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 132 "tokens.lex"
{ SAST(FUNC_NAME); }
	YY_BREAK
/* Basilisk C tokens */
case 53:
/* rule 53 can match eol */
YY_RULE_SETUP
#line 136 "tokens.lex"
{ SAST(NEW_FIELD); }
	YY_BREAK
case 54:
/* rule 54 can match eol */
YY_RULE_SETUP
#line 137 "tokens.lex"
{ SAST(NEW_FIELD); }
	YY_BREAK
case 55:
/* rule 55 can match eol */
YY_RULE_SETUP
#line 138 "tokens.lex"
{ SAST(NEW_FIELD); }
	YY_BREAK
case 56:
/* rule 56 can match eol */
YY_RULE_SETUP
#line 139 "tokens.lex"
{ SAST(TYPEDEF_NAME); }
	YY_BREAK
case 57:
/* rule 57 can match eol */
YY_RULE_SETUP
#line 140 "tokens.lex"
{ SAST(TYPEDEF_NAME); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 141 "tokens.lex"
{ SAST(MAYBECONST); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 142 "tokens.lex"
{ SAST(IN); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 143 "tokens.lex"
{ SAST(TRACE); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 144 "tokens.lex"
{ SAST(REDUCTION); }
	YY_BREAK
case 62:
#line 147 "tokens.lex"
case 63:
YY_RULE_SETUP
#line 147 "tokens.lex"
{ SAST(FOREACH_INNER); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 149 "tokens.lex"
{ SAST(FOREACH_DIMENSION); }
	YY_BREAK
case 65:
#line 152 "tokens.lex"
case 66:
YY_RULE_SETUP
#line 152 "tokens.lex"
{ SAST(FOREACH); }
	YY_BREAK
/* End of Basilisk C tokens */
case 67:
YY_RULE_SETUP
#line 156 "tokens.lex"
{ SAST(check_type (parse)); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 158 "tokens.lex"
{ SAST(I_CONSTANT); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 159 "tokens.lex"
{ SAST(I_CONSTANT); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 160 "tokens.lex"
{ SAST(I_CONSTANT); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 161 "tokens.lex"
{ SAST(I_CONSTANT); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 163 "tokens.lex"
{ SAST(F_CONSTANT); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 164 "tokens.lex"
{ SAST(F_CONSTANT); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 165 "tokens.lex"
{ SAST(F_CONSTANT); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 166 "tokens.lex"
{ SAST(F_CONSTANT); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 167 "tokens.lex"
{ SAST(F_CONSTANT); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 168 "tokens.lex"
{ SAST(F_CONSTANT); }
	YY_BREAK
case 78:
/* rule 78 can match eol */
YY_RULE_SETUP
#line 170 "tokens.lex"
{ SAST(STRING_LITERAL); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 172 "tokens.lex"
{ SAST(ELLIPSIS); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 173 "tokens.lex"
{ SAST(RIGHT_ASSIGN); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 174 "tokens.lex"
{ SAST(LEFT_ASSIGN); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 175 "tokens.lex"
{ SAST(ADD_ASSIGN); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 176 "tokens.lex"
{ SAST(SUB_ASSIGN); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 177 "tokens.lex"
{ SAST(MUL_ASSIGN); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 178 "tokens.lex"
{ SAST(DIV_ASSIGN); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 179 "tokens.lex"
{ SAST(MOD_ASSIGN); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 180 "tokens.lex"
{ SAST(AND_ASSIGN); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 181 "tokens.lex"
{ SAST(XOR_ASSIGN); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 182 "tokens.lex"
{ SAST(OR_ASSIGN); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 183 "tokens.lex"
{ SAST(RIGHT_OP); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 184 "tokens.lex"
{ SAST(LEFT_OP); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 185 "tokens.lex"
{ SAST(INC_OP); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 186 "tokens.lex"
{ SAST(DEC_OP); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 187 "tokens.lex"
{ SAST(PTR_OP); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 188 "tokens.lex"
{ SAST(AND_OP); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 189 "tokens.lex"
{ SAST(OR_OP); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 190 "tokens.lex"
{ SAST(LE_OP); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 191 "tokens.lex"
{ SAST(GE_OP); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 192 "tokens.lex"
{ SAST(EQ_OP); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 193 "tokens.lex"
{ SAST(NE_OP); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 194 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 195 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 196 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 197 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 198 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 199 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 200 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 201 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 202 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 203 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 204 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 205 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 206 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 207 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 208 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 209 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 210 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 211 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 212 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 213 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 214 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 215 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 216 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 217 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 125:
/* rule 125 can match eol */
YY_RULE_SETUP
#line 219 "tokens.lex"
{ /* whitespace separates tokens */ }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 220 "tokens.lex"
{ /* discard bad characters */ }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 222 "tokens.lex"
ECHO;
	YY_BREAK
#line 1878 "tokens.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 521 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 521 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 520);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 222 "tokens.lex"


static void comment (void)
{
  int c;  
  while ((c = input()) != 0)
    if (c == '*') {
      while ((c = input()) == '*')
	;
      
      if (c == '/')
	return;
      
      if (c == 0)
	break;
    }
  //  yyerror ("unterminated comment");
}

static void preproc (void)
{
  int c, c1 = 0;
  while ((c = input()) != 0) {
    if (c == '\n' && c1 != '\\')      
      return;
    c1 = c;
  }
  //  yyerror ("unterminated preprocessor directive");
}

static void bpreproc (void)
{
  int c;
  while ((c = input()) != 0)
    if (c == '@')
      return;
  //  yyerror ("unterminated @def");
}

static void ompreproc (void)
{
  int c, scope = 1;
  while ((c = input()) != 0) {
    if (c == '(')
      scope++;
    else if (c == ')') {
      scope--;
      if (scope == 0)
	return;
    }
  }
  //  yyerror ("unterminated OMP");
}

static void file_line (AstRoot * parse, const char * text)
{
  char * s = strchr (text, '#') + 1;
  yylineno = atoi(s) - 1;
  s = strchr (s, '"') + 1;
  char * end = strchr (s, '"');
  parse->nf++;
  parse->file = realloc (parse->file, parse->nf*sizeof (char *));
  char * file = calloc (end - s + 1, sizeof (char));
  parse->file[parse->nf - 1] = file;
  strncpy (file, s, end - s);
  //  fprintf (stderr, "%s: \"%s\" %d\n", text, file, yylineno);
}

static int check_type (AstRoot * parse)
{
  if (parse->type_already_specified)
    return IDENTIFIER;
  
  Ast * declaration = ast_identifier_declaration (parse->stack, yytext);
  if (declaration) {
    if (ast_is_typedef (declaration))
      return TYPEDEF_NAME;
    return IDENTIFIER;
  }

  return IDENTIFIER;
}

void lexer_setup (char * buffer, size_t len)
{
  yylineno = 1;
  yy_scan_buffer (buffer, len);
}

