#line 2 "tokens.c"

#line 4 "tokens.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yyget_lval
#define yyget_lval_ALREADY_DEFINED
#else
#define yyget_lval yyget_lval
#endif

#ifdef yyset_lval
#define yyset_lval_ALREADY_DEFINED
#else
#define yyset_lval yyset_lval
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 128
#define YY_END_OF_BUFFER 129
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[534] =
    {   0,
        0,    0,  129,  127,  126,  126,  114,  127,  120,  113,
      127,  108,  109,  118,  117,  105,  116,  112,  119,   71,
       70,  106,  102,  121,  107,  122,  125,   68,   68,  110,
      111,  123,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,  103,
      124,  104,  115,  126,    4,    6,   68,  101,    0,   79,
        0,   87,  104,   96,   88,    0,    0,    0,   85,   93,
       83,   94,   84,   95,    0,   74,    1,    2,   86,   75,
       71,    0,    0,   71,   71,    0,   71,   70,   70,   70,
       70,  111,  103,  110,   92,   98,  100,   99,   91,   68,

        0,    0,   89,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   15,   68,
       68,   68,   68,   68,   68,   68,   23,   59,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   90,   97,    0,    4,    6,    0,    0,    6,
        6,    6,   68,   79,    0,    0,    0,    0,   72,    0,
        0,    0,   80,    0,   74,    2,    0,   75,    0,   73,
       71,   71,   71,   71,    0,   69,   70,   70,   70,   70,
       82,   81,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,

       68,   68,   68,   68,   68,   21,   68,   68,   25,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,    0,
        0,    6,   68,    0,    0,    0,    0,    0,    0,   74,
        0,   75,   73,   71,    0,    0,   69,    0,   69,   69,
       70,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,    8,   68,   10,   11,   68,   68,   68,   68,
       17,   18,   68,   68,   68,   68,   22,   68,   26,    0,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   39,   68,   68,    0,    0,

        6,    0,    7,    0,    0,    0,    0,    0,    0,    0,
       69,   69,    0,   76,   69,   69,   68,   68,   45,   68,
       68,   68,   68,   68,   68,   68,   68,    9,   12,   68,
       68,   68,   68,    0,   20,   68,   68,    0,    0,    0,
        0,   68,   68,   68,   68,   30,   68,   68,   68,   68,
       68,   60,   68,   37,   68,   68,   68,   41,    0,    5,
        0,    0,   77,    0,   78,   76,   69,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   16,
       19,    0,   68,   24,    0,    0,    0,    0,   68,   68,
       68,   29,   31,   32,   33,   34,   35,   68,   68,   68,

       68,    0,    3,    0,    5,   58,   77,   78,   68,   68,
       44,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       14,    0,   65,    0,    0,    0,    0,    0,   68,   68,
       68,   36,   68,    0,   68,    3,    0,    0,   42,   43,
       46,   47,   68,   68,   68,   68,   68,   52,   13,    0,
       68,    0,    0,    0,    0,    0,   68,   27,   28,   38,
        0,   40,    0,    0,   68,   49,   68,   68,   68,    0,
       66,   66,   66,   66,    0,    0,    0,    0,    0,   61,
        0,    0,    0,   48,   68,   68,   68,    0,   66,   66,
       66,   66,    0,   53,   55,   54,    0,    0,   68,   68,

       68,   56,   66,   66,   66,    0,    0,    0,   68,   68,
       68,   66,   66,   66,    0,   68,   51,   68,   62,   66,
       66,   57,   50,    0,   67,   66,   66,   66,   66,   66,
       63,   64,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    4,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
       36,   37,   38,   37,   37,   39,   40,   41,   42,   43,
       37,   37,   44,   45,   46,   37,   37,   47,   37,   37,
       48,   49,   50,   51,   52,    1,   53,   54,   55,   56,

       57,   58,   59,   60,   61,   37,   62,   63,   64,   65,
       66,   67,   37,   68,   69,   70,   71,   72,   73,   74,
       75,   76,   77,   78,   79,   80,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[81] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    1,    4,
        1,    1,    1,    1,    1,    1,    5,    1,    6,    6,
        7,    7,    1,    1,    1,    1,    1,    3,    1,    7,
        7,    7,    7,    7,    7,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    1,    3,    1,
        1,    8,    6,    6,    7,    7,    7,    6,    8,    8,
        8,    8,    8,    8,    9,    8,    8,    9,    8,    9,
        8,    9,    8,    9,    8,    8,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[552] =
    {   0,
        0,   79,  974,  975,  975,  975,  947,   76,   57,   76,
      923,  916,  975,  944,   73,  975,   74,   72,   85,  109,
      118,  942,  975,   87,  942,   70,  975,    0,   99,  975,
      975,  941,  146,  895,  897,   54,   49,   53,   70,  898,
       59,  897,  905,  904,   81,   78,  139,   93,  900,  975,
       93,  975,  975,  163,  957,  102,  918,  975,  157,  191,
      142,  975,  975,  975,  975,  124,  148,  891,  975,  975,
      975,  975,  975,  975,  939,  189,  975,    0,  975,  214,
      221,  266,  198,  161,  140,  938,  150,  274,  205,  162,
      193,  975,  975,  975,  928,  975,  975,  975,  927,    0,

      180,  903,  975,  187,  885,  884,  892,  884,  881,  876,
      885,  116,  874,  886,  873,  888,  875,  881,  867,  868,
      865,  865,  879,  867,  864,  861,    0,  191,  865,  856,
      210,  862,  126,   79,  866,  873,  858,  918,  204,  855,
      207,  861,  975,  975,  296,  919,  225,  880,  295,    0,
      243,  862,  875,  303,  911,  253,  313,    0,  975,  291,
        0,  851,  975,  308,  975,    0,  332,  975,  336,  344,
      272,  975,  876,  851,    0,  330,  288,  975,  874,  849,
      975,  975,  850,  844,  843,  844,  842,  853,  837,  851,
      835,  832,  830,  834,  846,  841,  829,  220,  843,  841,

      837,  829,  835,  834,  837,  832,  822,  826,    0,  827,
      368,  814,  823,  813,  811,  813,  815,  822,  808,  806,
      806,  820,  817,  807,  811,  801,  814,  816,  805,  824,
      365,  808,  310,  362,  406,  370,  455,  796,  384,  394,
      401,  459,  975,  975,  215,  259,  353,  428,  297,  372,
      975,  805,  799,  799,  794,  803,  800,  801,  787,  799,
      785,  789,    0,  791,    0,    0,  782,  790,  779,  786,
        0,    0,  780,  392,  777,  793,    0,  780,    0,  465,
      789,  774,  774,  773,  770,  782,  772,  776,  781,  780,
      777,  777,  767,  772,  773,    0,  759,  771,  333,  428,

      825,  339,  975,  182,    0,  329,    0,  756,  481,  505,
      329,  975,  451,  509,  786,  761,  758,  761,    0,  758,
      752,  758,  748,  756,  763,  747,  759,    0,    0,  748,
      749,  754,  745,  480,    0,  754,  751,  754,  751,  748,
      747,  733,  732,  740,  735,    0,  743,  740,  742,  726,
      735,    0,  737,    0,  728,  718,  730,    0,  382,    0,
      778,  519,  534,  538,  542,  975,  975,  379,  734,  720,
      715,  709,  693,  700,  690,  667,  673,  653,  652,    0,
        0,  661,  657,    0,  660,  652,  629,  398,  631,  626,
      620,    0,    0,    0,    0,    0,    0,  616,  616,  406,

      608,  450,    0,  472,    0,  975,  975,  975,  601,  611,
        0,  594,  612,  613,  597,  612,  611,  608,  609,  595,
        0,  596,  598,  592,  585,  578,  576,  571,  574,  571,
      568,    0,  581,  547,  579,    0,  487,    0,    0,    0,
        0,    0,  567,  569,  580,  569,  560,    0,    0,  560,
      563,  512,  574,  560,  559,  567,  558,    0,    0,    0,
      567,    0,  559,  623,  546,    0,  548,  549,  544,  543,
        0,  547,  545,  547,  587,  531,  530,  528,  506,    0,
      523,  526,    0,    0,  505,  516,  513,  500,    0,  505,
      483,  484,  486,  975,  975,  975,  584,  479,  476,  467,

      466,  975,  442,  439,  399,  399,  591,  398,  378,  354,
      346,  335,  312,  301,  236,  205,    0,  599,    0,  194,
      172,  975,    0,  609,  975,  154,  133,   78,   54,   23,
        0,    0,  975,  681,  690,  694,  703,  710,  717,  726,
      731,  733,  735,  737,  744,  753,  762,  769,  773,  775,
      779
    } ;

static const flex_int16_t yy_def[552] =
    {   0,
      533,    1,  533,  533,  533,  533,  533,  534,  533,  533,
      535,  533,  533,  533,  533,  533,  533,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  536,  536,  533,
      533,  533,  536,  536,  536,  536,  536,  536,  536,  536,
      536,  536,  536,  536,  536,  536,  536,  536,  536,  533,
      533,  533,  533,  533,  533,  537,  536,  533,  534,  533,
      538,  533,  533,  533,  533,  535,  539,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  540,  533,  533,
      533,  533,  533,  533,  533,  541,  533,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  533,  533,  536,

      534,  535,  533,  536,  536,  536,  536,  536,  536,  536,
      536,  536,  536,  536,  536,  536,  536,  536,  536,  536,
      536,  536,  536,  536,  536,  536,  536,  536,  536,  536,
      536,  536,  536,  536,  536,  536,  536,  536,  536,  536,
      536,  536,  533,  533,  533,  533,  537,  533,  533,  537,
      537,  537,  536,  533,  533,  533,  534,  542,  533,  535,
      543,  533,  533,  533,  533,  540,  533,  533,  533,  533,
      533,  533,  533,  533,  544,  541,  533,  533,  533,  533,
      533,  533,  536,  536,  536,  536,  536,  536,  536,  536,
      536,  536,  536,  536,  536,  536,  536,  536,  536,  536,

      536,  536,  536,  536,  536,  536,  536,  536,  536,  536,
      536,  536,  536,  536,  536,  536,  536,  536,  536,  536,
      536,  536,  536,  536,  536,  536,  536,  536,  536,  533,
      533,  537,  536,  534,  534,  535,  535,  533,  533,  533,
      533,  533,  533,  533,  544,  544,  533,  533,  533,  533,
      533,  536,  536,  536,  536,  536,  536,  536,  536,  536,
      536,  536,  536,  536,  536,  536,  536,  536,  536,  536,
      536,  536,  536,  536,  536,  536,  536,  536,  536,  533,
      536,  536,  536,  536,  536,  536,  536,  536,  536,  536,
      536,  536,  536,  536,  536,  536,  536,  536,  533,  533,

      537,  533,  533,  534,  235,  535,  237,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  536,  536,  536,  536,
      536,  536,  536,  536,  536,  536,  536,  536,  536,  536,
      536,  536,  536,  533,  536,  536,  536,  533,  533,  533,
      533,  536,  536,  536,  536,  536,  536,  536,  536,  536,
      536,  536,  536,  536,  536,  536,  536,  536,  545,  546,
      533,  533,  533,  533,  533,  533,  533,  536,  536,  536,
      536,  536,  536,  536,  536,  536,  536,  536,  536,  536,
      536,  533,  536,  536,  533,  533,  533,  533,  536,  536,
      536,  536,  536,  536,  536,  536,  536,  536,  536,  536,

      536,  545,  547,  548,  546,  533,  533,  533,  536,  536,
      536,  536,  536,  536,  536,  536,  536,  536,  536,  536,
      536,  533,  536,  533,  533,  533,  533,  533,  536,  536,
      536,  536,  536,  533,  536,  547,  545,  549,  536,  536,
      536,  536,  536,  536,  536,  536,  536,  536,  536,  533,
      550,  533,  533,  533,  533,  533,  536,  536,  536,  536,
      533,  536,  545,  545,  536,  536,  536,  536,  536,  533,
      551,  551,  551,  551,  533,  533,  533,  533,  533,  536,
      533,  545,  464,  536,  536,  536,  536,  533,  551,  551,
      551,  551,  533,  533,  533,  533,  533,  533,  536,  536,

      536,  533,  551,  551,  551,  533,  533,  533,  536,  536,
      536,  551,  551,  551,  533,  536,  536,  536,  551,  551,
      551,  533,  536,  533,  533,  551,  551,  551,  551,  551,
      551,  551,    0,  533,  533,  533,  533,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,
      533
    } ;

static const flex_int16_t yy_nxt[1056] =
    {   0,
        4,    5,    6,    5,    7,    8,    4,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       21,   21,   22,   23,   24,   25,   26,   27,    4,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   29,   28,
       28,   28,   28,   28,   28,   29,   28,   30,    4,   31,
       32,   33,   34,   35,   36,   37,   38,   39,   40,   28,
       41,   28,   42,   28,   43,   28,   28,   44,   45,   46,
       47,   48,   49,   28,   28,   28,   50,   51,   52,   53,
       54,   60,   62,   63,   64,   55,   70,  532,   75,   72,
       76,   76,   76,   76,   93,   98,   99,   77,   71,   73,

       74,   65,   78,  151,  101,  118,  115,   56,  102,   94,
       79,   95,   96,  116,  119,  120,  127,  121,  143,  117,
       57,  531,  123,  128,   61,   80,  122,   81,   81,   82,
       82,  219,  124,  159,   80,  125,   88,   88,   88,   88,
      132,  133,   83,  530,  101,  136,  220,   84,  102,  140,
      134,   83,  137,  135,   85,   86,   89,  152,  141,  138,
      157,  157,   60,   90,  145,   83,  160,  160,  192,  146,
      144,   87,   67,  193,   83,  104,  105,  106,  173,   85,
       91,  107,   86,  108,  217,   60,  109,   60,   90,  110,
      111,  147,  154,  154,  154,  172,  101,  112,  529,  171,

      179,  218,  174,  139,  148,   61,  172,   76,   76,   76,
       76,  169,  171,  169,  528,  158,  170,  170,  170,  170,
      172,  161,  164,  165,  180,  527,  151,  165,   61,  155,
       61,  172,   76,   76,   76,   76,  155,   80,  178,   81,
       81,   82,   82,  177,  151,  164,  165,  167,  168,  183,
      178,  165,  168,  208,   83,  177,  184,  309,  101,   84,
      209,  156,  526,  178,  224,  212,   85,  227,  213,  228,
      167,  168,  225,  155,  523,  178,  168,   83,  214,  215,
      152,  309,   80,   87,   82,   82,   82,   82,  267,  268,
       80,   85,   88,   88,   88,   88,  149,  145,  152,   83,

      159,  310,  146,  522,  154,  154,  154,   83,  101,  236,
      236,  302,   89,  231,  231,  231,  231,  172,   60,   90,
      303,  239,   83,  239,  147,  310,  240,  240,  240,  240,
       83,  234,  234,  178,  302,  315,   91,  148,  159,   67,
      302,  155,  172,  303,   90,  241,  246,  241,  155,  303,
      242,  242,  242,  242,  170,  170,  170,  170,  178,  316,
      521,   61,  170,  170,  170,  170,  300,   60,  247,  280,
      280,  280,  248,  156,  312,  249,  520,   67,  243,  159,
      304,  304,  243,  231,  231,  231,  231,  403,  306,  306,
      519,  311,  250,  334,  334,  334,  248,  518,  312,  312,

      249,  243,  240,  240,  240,  240,  243,  434,  434,  434,
       61,   60,  240,  240,  240,  240,  517,  312,   67,  242,
      242,  242,  242,  312,  305,  305,  305,  305,  165,  300,
      404,  409,  165,  359,  311,  305,  305,  305,  305,  305,
      305,  313,  312,  313,  410,  516,  314,  314,  314,  314,
      515,  165,  427,  427,   61,  403,  165,  514,  305,  305,
      305,  305,  305,  305,  159,  428,  280,  280,  280,  314,
      314,  314,  314,  307,  307,  307,  307,  242,  242,  242,
      242,  334,  334,  334,  307,  307,  307,  307,  307,  307,
      437,  437,  403,  168,  362,  513,  362,  168,  404,  363,

      363,  363,  363,   67,  512,  463,  463,  307,  307,  307,
      307,  307,  307,  475,  475,  475,  168,  511,  364,  510,
      364,  168,  338,  365,  365,  365,  365,  314,  314,  314,
      314,  403,  509,  339,  340,  404,  341,  363,  363,  363,
      363,  508,  506,  366,  505,  438,  504,  366,  434,  434,
      434,  382,  363,  363,  363,  363,  365,  365,  365,  365,
      365,  365,  365,  365,  403,  503,  366,  502,  407,  501,
      500,  366,  407,  499,  404,  498,  408,  482,  482,  497,
      408,  100,  100,  100,  100,  507,  507,  507,  475,  475,
      475,  407,  507,  507,  507,  496,  407,  495,  494,  408,

      524,  524,  524,  492,  408,  491,  490,  404,  488,  525,
      524,  524,  524,  487,  486,  461,  485,  472,  473,  525,
      484,  481,  480,  479,  478,  477,  476,  474,  403,  470,
      469,  468,  467,  466,  465,  462,  460,  459,  458,  457,
      456,  483,  483,  483,  483,  455,  454,  453,  452,  451,
      450,  449,  483,  483,  483,  483,  483,  483,  493,  339,
      448,  447,  446,  445,  444,  443,  442,  441,  440,  439,
      435,  404,  433,  432,  431,  483,  483,  483,  483,  483,
      483,   59,  430,   59,   59,   59,   59,   59,   59,   59,
       66,  429,   66,  426,   66,   66,   66,   66,   66,  100,

      100,  100,  100,  150,  425,  150,  150,  150,  150,  150,
      150,  150,   59,   59,  424,   59,  423,  422,   59,   66,
       66,  421,   66,  420,  419,   66,  166,  418,  166,  166,
      166,  166,  166,  166,  166,  176,  176,  176,  235,  235,
      237,  237,  245,  245,  402,  417,  402,  402,  402,  402,
      402,  402,  402,  405,  416,  405,  405,  405,  405,  405,
      405,  405,  436,  415,  436,  436,  436,  436,  436,  436,
      436,  402,  402,  414,  402,  413,  412,  402,  464,  464,
      471,  471,  471,  471,  489,  489,  489,  489,  411,  406,
      401,  400,  399,  398,  397,  396,  395,  394,  393,  392,

      391,  390,  389,  388,  387,  386,  385,  384,  383,  381,
      380,  379,  378,  377,  376,  375,  374,  373,  372,  371,
      370,  369,  368,  367,  367,  361,  360,  358,  357,  356,
      355,  354,  353,  352,  351,  350,  349,  348,  347,  346,
      345,  344,  343,  342,  337,  336,  335,  333,  332,  331,
      330,  329,  328,  327,  326,  325,  324,  323,  322,  321,
      320,  319,  318,  317,  308,  301,  299,  298,  297,  296,
      295,  294,  293,  292,  291,  290,  289,  288,  287,  286,
      285,  284,  283,  282,  281,  279,  278,  277,  276,  275,
      274,  273,  272,  271,  270,  269,  266,  265,  264,  263,

      262,  261,  260,  259,  258,  257,  256,  255,  254,  253,
      252,  251,  251,  244,  244,  238,  101,  233,  232,  230,
      149,  229,  226,  101,  223,  222,  221,  216,  211,  210,
      207,  206,  205,  204,  203,  202,  201,  200,  199,  198,
      197,  196,  195,  194,  191,  190,  189,  188,  187,  186,
      185,   67,  182,  181,  175,  163,  162,  153,  149,  142,
      131,  130,  129,  126,  114,  113,  103,   97,   92,   69,
       68,   67,   58,  533,    3,  533,  533,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,

      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,
      533,  533,  533,  533,  533
    } ;

static const flex_int16_t yy_chk[1056] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        2,    8,    9,    9,   10,    2,   15,  530,   18,   17,
       18,   18,   18,   18,   24,   26,   26,   19,   15,   17,

       17,   10,   19,   56,   29,   37,   36,    2,   29,   24,
       19,   24,   24,   36,   37,   38,   41,   38,   51,   36,
        2,  529,   39,   41,    8,   20,   38,   20,   20,   20,
       20,  134,   39,   66,   21,   39,   21,   21,   21,   21,
       45,   45,   20,  528,   47,   46,  134,   20,   47,   48,
       45,   21,   46,   45,   20,   20,   21,   56,   48,   47,
       61,   61,   59,   21,   54,   20,   67,   67,  112,   54,
       51,   20,   66,  112,   21,   33,   33,   33,   85,   20,
       21,   33,   20,   33,  133,  101,   33,  304,   21,   33,
       33,   54,   60,   60,   60,   87,   60,   33,  527,   84,

       90,  133,   85,   47,   54,   59,   84,   76,   76,   76,
       76,   83,   87,   83,  526,   61,   83,   83,   83,   83,
       87,   67,   76,   76,   90,  521,  147,   76,  101,   60,
      304,   84,   80,   80,   80,   80,   60,   81,   91,   81,
       81,   81,   81,   89,  151,   76,   76,   80,   80,  104,
       89,   76,   80,  128,   81,   91,  104,  245,  156,   81,
      128,   60,  520,   91,  139,  131,   81,  141,  131,  141,
       80,   80,  139,  156,  516,   89,   80,   81,  131,  131,
      147,  245,   82,   81,   82,   82,   82,   82,  198,  198,
       88,   81,   88,   88,   88,   88,  149,  145,  151,   82,

      160,  246,  145,  515,  154,  154,  154,   88,  154,  160,
      160,  233,   88,  149,  149,  149,  149,  171,  157,   88,
      233,  164,   82,  164,  145,  246,  164,  164,  164,  164,
       88,  157,  157,  177,  299,  249,   88,  145,  306,  160,
      302,  154,  171,  299,   88,  167,  176,  167,  154,  302,
      167,  167,  167,  167,  169,  169,  169,  169,  177,  249,
      514,  157,  170,  170,  170,  170,  231,  234,  176,  211,
      211,  211,  176,  154,  311,  176,  513,  306,  170,  236,
      234,  234,  170,  231,  231,  231,  231,  359,  236,  236,
      512,  247,  176,  274,  274,  274,  176,  511,  247,  311,

      176,  170,  239,  239,  239,  239,  170,  400,  400,  400,
      234,  235,  240,  240,  240,  240,  510,  250,  236,  241,
      241,  241,  241,  247,  235,  235,  235,  235,  240,  300,
      359,  368,  240,  300,  250,  235,  235,  235,  235,  235,
      235,  248,  250,  248,  368,  509,  248,  248,  248,  248,
      508,  240,  388,  506,  235,  402,  240,  505,  235,  235,
      235,  235,  235,  235,  237,  388,  280,  280,  280,  313,
      313,  313,  313,  237,  237,  237,  237,  242,  242,  242,
      242,  334,  334,  334,  237,  237,  237,  237,  237,  237,
      404,  404,  437,  242,  309,  504,  309,  242,  402,  309,

      309,  309,  309,  237,  503,  437,  437,  237,  237,  237,
      237,  237,  237,  452,  452,  452,  242,  501,  310,  500,
      310,  242,  280,  310,  310,  310,  310,  314,  314,  314,
      314,  482,  499,  280,  280,  437,  280,  362,  362,  362,
      362,  498,  493,  314,  492,  404,  491,  314,  434,  434,
      434,  334,  363,  363,  363,  363,  364,  364,  364,  364,
      365,  365,  365,  365,  463,  490,  314,  488,  363,  487,
      486,  314,  363,  485,  482,  481,  365,  463,  463,  479,
      365,  451,  451,  451,  451,  497,  497,  497,  475,  475,
      475,  363,  507,  507,  507,  478,  363,  477,  476,  365,

      518,  518,  518,  474,  365,  473,  472,  463,  470,  518,
      524,  524,  524,  469,  468,  434,  467,  451,  451,  524,
      465,  461,  457,  456,  455,  454,  453,  451,  464,  450,
      447,  446,  445,  444,  443,  435,  433,  431,  430,  429,
      428,  464,  464,  464,  464,  427,  426,  425,  424,  423,
      422,  420,  464,  464,  464,  464,  464,  464,  475,  507,
      419,  418,  417,  416,  415,  414,  413,  412,  410,  409,
      401,  464,  399,  398,  391,  464,  464,  464,  464,  464,
      464,  534,  390,  534,  534,  534,  534,  534,  534,  534,
      535,  389,  535,  387,  535,  535,  535,  535,  535,  536,

      536,  536,  536,  537,  386,  537,  537,  537,  537,  537,
      537,  537,  538,  538,  385,  538,  383,  382,  538,  539,
      539,  379,  539,  378,  377,  539,  540,  376,  540,  540,
      540,  540,  540,  540,  540,  541,  541,  541,  542,  542,
      543,  543,  544,  544,  545,  375,  545,  545,  545,  545,
      545,  545,  545,  546,  374,  546,  546,  546,  546,  546,
      546,  546,  547,  373,  547,  547,  547,  547,  547,  547,
      547,  548,  548,  372,  548,  371,  370,  548,  549,  549,
      550,  550,  550,  550,  551,  551,  551,  551,  369,  361,
      357,  356,  355,  353,  351,  350,  349,  348,  347,  345,

      344,  343,  342,  341,  340,  339,  338,  337,  336,  333,
      332,  331,  330,  327,  326,  325,  324,  323,  322,  321,
      320,  318,  317,  316,  315,  308,  301,  298,  297,  295,
      294,  293,  292,  291,  290,  289,  288,  287,  286,  285,
      284,  283,  282,  281,  278,  276,  275,  273,  270,  269,
      268,  267,  264,  262,  261,  260,  259,  258,  257,  256,
      255,  254,  253,  252,  238,  232,  230,  229,  228,  227,
      226,  225,  224,  223,  222,  221,  220,  219,  218,  217,
      216,  215,  214,  213,  212,  210,  208,  207,  206,  205,
      204,  203,  202,  201,  200,  199,  197,  196,  195,  194,

      193,  192,  191,  190,  189,  188,  187,  186,  185,  184,
      183,  180,  179,  174,  173,  162,  155,  153,  152,  148,
      146,  142,  140,  138,  137,  136,  135,  132,  130,  129,
      126,  125,  124,  123,  122,  121,  120,  119,  118,  117,
      116,  115,  114,  113,  111,  110,  109,  108,  107,  106,
      105,  102,   99,   95,   86,   75,   68,   57,   55,   49,
       44,   43,   42,   40,   35,   34,   32,   25,   22,   14,
       12,   11,    7,    3,  533,  533,  533,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,

      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,
      533,  533,  533,  533,  533,  533,  533,  533,  533,  533,
      533,  533,  533,  533,  533
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[129] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "tokens.lex"
/**
# Lexer for Basilisk C

Closely based on the [C99 lexer](c.lex). */
#line 33 "tokens.lex"
#include <stdio.h>
#include <assert.h>
#include "parser.h"
#include "basilisk.h"

#define YYSTYPE Ast *
#define YY_DECL int yylex (YYSTYPE * yylval_param, AstRoot * parse)
 
static void comment (void);
static void preproc (void);
static void bpreproc (void);
static void ompreproc (void);
static void file_line (AstRoot * parse, const char * text);
static int  check_type (AstRoot * parse);

static Ast * new_ast (AstRoot * parse,
		      int token, int line, char * start, char * end)
{
  Allocator * alloc = parse->alloc;
  Ast * n = allocate (alloc, sizeof(AstTerminal));
  memset (n, 0, sizeof(AstTerminal));
  n->sym = token_symbol (token);
  AstTerminal * t = ast_terminal (n);
  t->start = start;
  t->after = end;
  t->file = parse->file[parse->nf - 1];
  while (start != end) {
    if (*start == '\n')
      line--;
    start++;
  }
  t->line = line;
  return n;
}

#define CAST()								\
  *yylval = new_ast (parse, yytext[0], yylineno, yytext, yytext);	\
  return yytext[0];
  
#define SAST(t) 							\
  *yylval = new_ast (parse, t, yylineno, yytext, yytext + strlen(yytext) - 1); \
  return t;
  
#line 950 "tokens.c"
#line 951 "tokens.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

YYSTYPE * yyget_lval ( void );

void yyset_lval ( YYSTYPE * yylval_param  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex \
               (YYSTYPE * yylval_param );

#define YY_DECL int yylex \
               (YYSTYPE * yylval_param )
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
        YYSTYPE * yylval;
    
    yylval = yylval_param;

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 78 "tokens.lex"


#line 1182 "tokens.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 534 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 975 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 80 "tokens.lex"
{ comment(); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 81 "tokens.lex"
{ /* consume //-comment */ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 82 "tokens.lex"
{ file_line (parse, yytext); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 83 "tokens.lex"
{ preproc(); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 84 "tokens.lex"
{ bpreproc(); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 85 "tokens.lex"

	YY_BREAK
case 7:
YY_RULE_SETUP
#line 86 "tokens.lex"
{ ompreproc(); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 88 "tokens.lex"
{ SAST(AUTO); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 89 "tokens.lex"
{ SAST(BREAK); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 90 "tokens.lex"
{ SAST(CASE); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 91 "tokens.lex"
{ SAST(CHAR); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 92 "tokens.lex"
{ SAST(CONST); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 93 "tokens.lex"
{ SAST(CONTINUE); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 94 "tokens.lex"
{ SAST(DEFAULT); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 95 "tokens.lex"
{ SAST(DO); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 96 "tokens.lex"
{ SAST(DOUBLE); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 97 "tokens.lex"
{ SAST(ELSE); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 98 "tokens.lex"
{ SAST(ENUM); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 99 "tokens.lex"
{ SAST(EXTERN); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 100 "tokens.lex"
{ SAST(FLOAT); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 101 "tokens.lex"
{ SAST(FOR); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 102 "tokens.lex"
{ SAST(GOTO); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 103 "tokens.lex"
{ SAST(IF); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 104 "tokens.lex"
{ SAST(INLINE); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 105 "tokens.lex"
{ SAST(INT); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 106 "tokens.lex"
{ SAST(LONG); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 107 "tokens.lex"
{ SAST(REGISTER); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 108 "tokens.lex"
{ SAST(RESTRICT); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 109 "tokens.lex"
{ SAST(RETURN); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 110 "tokens.lex"
{ SAST(SHORT); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 111 "tokens.lex"
{ SAST(SIGNED); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 112 "tokens.lex"
{ SAST(SIZEOF); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 113 "tokens.lex"
{ SAST(STATIC); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 114 "tokens.lex"
{ SAST(STRUCT); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 115 "tokens.lex"
{ SAST(SWITCH); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 116 "tokens.lex"
{ SAST(TYPEDEF); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 117 "tokens.lex"
{ SAST(UNION); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 118 "tokens.lex"
{ SAST(UNSIGNED); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 119 "tokens.lex"
{ SAST(VOID); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 120 "tokens.lex"
{ SAST(VOLATILE); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 121 "tokens.lex"
{ SAST(WHILE); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 122 "tokens.lex"
{ SAST(ALIGNAS); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 123 "tokens.lex"
{ SAST(ALIGNOF); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 124 "tokens.lex"
{ SAST(ATOMIC); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 125 "tokens.lex"
{ SAST(BOOL); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 126 "tokens.lex"
{ SAST(COMPLEX); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 127 "tokens.lex"
{ SAST(GENERIC); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 128 "tokens.lex"
{ SAST(IMAGINARY); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 129 "tokens.lex"
{ SAST(NORETURN); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 130 "tokens.lex"
{ SAST(STATIC_ASSERT); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 131 "tokens.lex"
{ SAST(THREAD_LOCAL); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 132 "tokens.lex"
{ SAST(FUNC_NAME); }
	YY_BREAK
/* Basilisk C tokens */
case 53:
/* rule 53 can match eol */
YY_RULE_SETUP
#line 136 "tokens.lex"
{ SAST(NEW_FIELD); }
	YY_BREAK
case 54:
/* rule 54 can match eol */
YY_RULE_SETUP
#line 137 "tokens.lex"
{ SAST(NEW_FIELD); }
	YY_BREAK
case 55:
/* rule 55 can match eol */
YY_RULE_SETUP
#line 138 "tokens.lex"
{ SAST(NEW_FIELD); }
	YY_BREAK
case 56:
/* rule 56 can match eol */
YY_RULE_SETUP
#line 139 "tokens.lex"
{ SAST(TYPEDEF_NAME); }
	YY_BREAK
case 57:
/* rule 57 can match eol */
YY_RULE_SETUP
#line 140 "tokens.lex"
{ SAST(TYPEDEF_NAME); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 141 "tokens.lex"
{ SAST(MAYBECONST); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 142 "tokens.lex"
{ SAST(IN); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 143 "tokens.lex"
{ SAST(TRACE); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 144 "tokens.lex"
{ SAST(REDUCTION); }
	YY_BREAK
case 62:
#line 147 "tokens.lex"
case 63:
YY_RULE_SETUP
#line 147 "tokens.lex"
{ SAST(FOREACH_INNER); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 149 "tokens.lex"
{ SAST(FOREACH_DIMENSION); }
	YY_BREAK
case 65:
#line 152 "tokens.lex"
case 66:
YY_RULE_SETUP
#line 152 "tokens.lex"
{ SAST(FOREACH); }
	YY_BREAK
/* GCC extensions */
case 67:
/* rule 67 can match eol */
YY_RULE_SETUP
#line 156 "tokens.lex"
{ ompreproc(); }
	YY_BREAK
/* End of GCC extensions */
case 68:
YY_RULE_SETUP
#line 160 "tokens.lex"
{ SAST(check_type (parse)); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 162 "tokens.lex"
{ SAST(I_CONSTANT); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 163 "tokens.lex"
{ SAST(I_CONSTANT); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 164 "tokens.lex"
{ SAST(I_CONSTANT); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 165 "tokens.lex"
{ SAST(I_CONSTANT); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 167 "tokens.lex"
{ SAST(F_CONSTANT); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 168 "tokens.lex"
{ SAST(F_CONSTANT); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 169 "tokens.lex"
{ SAST(F_CONSTANT); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 170 "tokens.lex"
{ SAST(F_CONSTANT); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 171 "tokens.lex"
{ SAST(F_CONSTANT); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 172 "tokens.lex"
{ SAST(F_CONSTANT); }
	YY_BREAK
case 79:
/* rule 79 can match eol */
YY_RULE_SETUP
#line 174 "tokens.lex"
{ SAST(STRING_LITERAL); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 176 "tokens.lex"
{ SAST(ELLIPSIS); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 177 "tokens.lex"
{ SAST(RIGHT_ASSIGN); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 178 "tokens.lex"
{ SAST(LEFT_ASSIGN); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 179 "tokens.lex"
{ SAST(ADD_ASSIGN); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 180 "tokens.lex"
{ SAST(SUB_ASSIGN); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 181 "tokens.lex"
{ SAST(MUL_ASSIGN); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 182 "tokens.lex"
{ SAST(DIV_ASSIGN); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 183 "tokens.lex"
{ SAST(MOD_ASSIGN); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 184 "tokens.lex"
{ SAST(AND_ASSIGN); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 185 "tokens.lex"
{ SAST(XOR_ASSIGN); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 186 "tokens.lex"
{ SAST(OR_ASSIGN); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 187 "tokens.lex"
{ SAST(RIGHT_OP); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 188 "tokens.lex"
{ SAST(LEFT_OP); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 189 "tokens.lex"
{ SAST(INC_OP); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 190 "tokens.lex"
{ SAST(DEC_OP); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 191 "tokens.lex"
{ SAST(PTR_OP); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 192 "tokens.lex"
{ SAST(AND_OP); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 193 "tokens.lex"
{ SAST(OR_OP); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 194 "tokens.lex"
{ SAST(LE_OP); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 195 "tokens.lex"
{ SAST(GE_OP); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 196 "tokens.lex"
{ SAST(EQ_OP); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 197 "tokens.lex"
{ SAST(NE_OP); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 198 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 199 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 200 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 201 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 202 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 203 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 204 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 205 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 206 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 207 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 208 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 209 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 210 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 211 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 212 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 213 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 214 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 215 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 216 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 217 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 218 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 219 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 220 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 221 "tokens.lex"
{ CAST(); }
	YY_BREAK
case 126:
/* rule 126 can match eol */
YY_RULE_SETUP
#line 223 "tokens.lex"
{ /* whitespace separates tokens */ }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 224 "tokens.lex"
{ /* discard bad characters */ }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 226 "tokens.lex"
ECHO;
	YY_BREAK
#line 1895 "tokens.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 534 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 534 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 533);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 226 "tokens.lex"


static void comment (void)
{
  int c;  
  while ((c = input()) != 0)
    if (c == '*') {
      while ((c = input()) == '*')
	;
      
      if (c == '/')
	return;
      
      if (c == 0)
	break;
    }
  //  yyerror ("unterminated comment");
}

static void preproc (void)
{
  int c, c1 = 0;
  while ((c = input()) != 0) {
    if (c == '\n' && c1 != '\\')      
      return;
    c1 = c;
  }
  //  yyerror ("unterminated preprocessor directive");
}

static void bpreproc (void)
{
  int c;
  while ((c = input()) != 0)
    if (c == '@')
      return;
  //  yyerror ("unterminated @def");
}

static void ompreproc (void)
{
  int c, scope = 1;
  while ((c = input()) != 0) {
    if (c == '(')
      scope++;
    else if (c == ')') {
      scope--;
      if (scope == 0)
	return;
    }
  }
  //  yyerror ("unterminated OMP");
}

static void file_line (AstRoot * parse, const char * text)
{
  char * s = strchr (text, '#') + 1;
  yylineno = atoi(s) - 1;
  s = strchr (s, '"') + 1;
  char * end = strchr (s, '"');
  parse->nf++;
  parse->file = realloc (parse->file, parse->nf*sizeof (char *));
  char * file = calloc (end - s + 1, sizeof (char));
  parse->file[parse->nf - 1] = file;
  strncpy (file, s, end - s);
  //  fprintf (stderr, "%s: \"%s\" %d\n", text, file, yylineno);
}

static int check_type (AstRoot * parse)
{
  if (parse->type_already_specified)
    return IDENTIFIER;
  
  Ast * declaration = ast_identifier_declaration (parse->stack, yytext);
  if (declaration) {
    if (ast_is_typedef (declaration))
      return TYPEDEF_NAME;
    return IDENTIFIER;
  }

  return IDENTIFIER;
}

void lexer_setup (char * buffer, size_t len)
{
  yylineno = 1;
  yy_scan_buffer (buffer, len);
}

