/**
# Check that unchanged values are not "unset" by undefined conditions. */

int main()
{
  int a, b[1] = {-1}, c = -1;
  if (a) // this is an undefined condition....
    b[0] = -1, c = -1;  // but this does change the values of b[0] or c...
  display_value (b[0]); // so this should not be "unset"...
  display_value (c); // and neither should this...
}
